# Generated by Django 4.0.6 on 2022-08-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ez_rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='k_factor',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='team',
            name='ranked_games_played',
            field=models.IntegerField(default=0),
        ),
    ]
