# Generated by Django 4.0.6 on 2022-08-06 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ez_rank', '0004_alter_team_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_abbr',
            field=models.CharField(default='XXX', max_length=3),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_score', models.IntegerField(default=0)),
                ('loser_score', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='game date')),
                ('team_loser', models.ManyToManyField(related_name='team_loser', to='ez_rank.team')),
                ('team_winner', models.ManyToManyField(related_name='team_winner', to='ez_rank.team')),
            ],
        ),
    ]
